services:
  - type: web
    name: madarek
    runtime: node
    plan: free
    region: oregon
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
